### ISSUE TITLE
 Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by sarus** [polarityio/ipinfo#1]
```
{
    "debug": {
        "stderr": "\nMessage: Cannot read property 'statusCode' of undefined\n\nStacktrace:\n====================\nTypeError: Cannot read property 'statusCode' of undefined\n    at Request._callback (/app/polarity-server/integrations/ipinfo/integration.js:43:28)\n    at self.callback (/app/polarity-server/integrations/ipinfo/node_modules/request/request.js:188:22)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at Request.onRequestError (/app/polarity-server/integrations/ipinfo/node_modules/request/request.js:884:8)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at TLSSocket.socketErrorListener (_http_client.js:309:9)\n    at emitOne (events.js:96:13)\n    at TLSSocket.emit (events.js:188:7)\n\n"
    },
    "md5": "cb37233a54b635aff635c4d6e865addf"
}
```

**Comment by sarus** [comment]
Should be resolved in 1.0.3-beta

https://github.com/polarityio/ipinfo/releases/tag/1.0.3-beta
